name: Secrets and Environment Variables

on:
  workflow_dispatch

jobs:
  top-secret:
    runs-on: ubuntu-latest
    
    steps:
      - name: Read a variable
        run: echo "My APP_ID value is ${{ vars.APP_ID }}"

      - name: Tell me a secret!
        run: echo "My existing secret is ${{ secrets.API_KEY }}"
      
      - name: Unset secret
        run: echo "My unknown secret is ${{ secrets.PYPI_API_TOKEN }}"
      
      - name: Github stuff
        run: echo "My Github repo is called ${{ github.repository }}"
      
      - name: Read an env variable
        run: echo "My APP_ID value is ${{ env.APP_ID }} (also accessible as $MY_APP_ID)"

      - uses: actions/checkout@v2
      - name: Read the env from an external script
        run: |
         chmod +x .github/scripts/custom.sh
         .github/scripts/custom.sh
        shell: bash
